name: weatherjourney
description: A new Flutter project.
publish_to: 'none'
version: 0.2.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^8.0.5
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.1.2
  google_fonts: ^4.0.4
  firebase_core: ^2.13.0
  firebase_auth: ^4.2.4
  freezed_annotation: ^2.2.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  dio: ^5.2.1+1
  retrofit: ^4.0.1
  cloud_firestore: ^4.8.2
  flutter_swipe_action_cell: ^3.1.2
  weather_pack: 0.0.2
  timezone: ^0.9.2
  the_apple_sign_in: ^1.1.1
  google_sign_in: ^6.1.4
  flutter_svg: ^2.0.7
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.2.5
  firebase_crashlytics: ^3.3.0
  firebase_performance: ^0.9.3+8
  geolocator: ^10.1.0
  pretty_dio_logger: ^1.3.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  freezed: ^2.3.5
  retrofit_generator: ^7.0.7
  test: ^1.24.9

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
  - assets/illustrations/
  - assets/icons/
  - assets/icons/weather/
  - assets/icons/menu/
