name: Release workflow

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Test
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      
      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test   
  update-codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Nécessaire pour récupérer tous les tags

      - name: Installing Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --coverage 

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          fail_ci_if_error: true


  release-android:
    environment: prod
    runs-on: ubuntu-latest
    needs: update-codecov
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Nécessaire pour récupérer tous les tags

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          rubygems: latest

      - name: Setup Android release key
        run: |
          echo ${{ secrets.KEY_BASE_64 }} | base64 --decode > android/app/key.jks
          echo keyPassword=\${{ secrets.KEY_PASSWORD }} > android/key.properties
          echo storePassword=\${{ secrets.STORE_PASSWORD }} >> android/key.properties
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> android/key.properties
        shell: bash

      - name: Setup PlayStore service account
        run: |
          echo ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT_BASE_64 }} | base64 --decode > android/playstore-service-account.json
        shell: bash

      - name: Deploy iOS Beta to TestFlight via Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: promote_beta_to_production
          subdirectory: android

  release-ios:
    environment: prod
    runs-on: macos-13
    needs: update-codecov
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Nécessaire pour récupérer tous les tags

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          rubygems: latest

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}

      - name: Download AppleAuthKey and GCloud KeyFile Json from GCP bucket
        run: |
          gsutil cp gs://'${{ secrets.GOOGLE_CLOUD_BUCKET_NAME }}'/'${{ secrets.APPLE_AUTH_KEY_FILENAME }}' ./ios/'${{ secrets.APPLE_AUTH_KEY_FILENAME }}'
          gsutil cp gs://'${{ secrets.GOOGLE_CLOUD_BUCKET_NAME }}'/'${{ secrets.GOOGLE_CLOUD_KEY_FILENAME }}' ./ios/'${{ secrets.GOOGLE_CLOUD_KEY_FILENAME }}'

      - name: Promote IOS Beta to Production
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: promote_to_app_store
          subdirectory: ios
        env:
          DEVELOPER_APP_IDENTIFIER: "${{ secrets.DEVELOPER_APP_IDENTIFIER }}"
          APPLE_DEVELOPER_USERNAME: "${{ secrets.APPLE_DEVELOPER_USERNAME }}"
          APPLE_AUTH_KEY_ID: "${{ secrets.APPLE_AUTH_KEY_ID }}"
          APPLE_AUTH_ISSUER_ID: "${{ secrets.APPLE_AUTH_ISSUER_ID }}"
          APPLE_AUTH_KEY_PATH: "${{ secrets.APPLE_AUTH_KEY_PATH }}"
          FASTLANE_APPLE_ID: "${{ secrets.FASTLANE_APPLE_ID }}"
          APP_STORE_CONNECT_TEAM_ID: "${{ secrets.APP_STORE_CONNECT_TEAM_ID }}"
          DEVELOPER_PORTAL_TEAM_ID: "${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}"
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: "${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}"
          MATCH_KEYCHAIN_PASSWORD: "${{ secrets.MATCH_KEYCHAIN_PASSWORD }}"
          GOOGLE_CLOUD_BUCKET_NAME: "${{ secrets.GOOGLE_CLOUD_BUCKET_NAME }}"
          GOOGLE_CLOUD_PROJECT_ID: "${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}"

  merge-main-to-develop:
    runs-on: ubuntu-latest
    needs: [release-android, release-ios]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Nécessaire pour récupérer tous les tags

      - name: Merge main to develop
        run: |
          git config --local user.email "ci-executor@github.com"
          git config --local user.name "GitHub Action"
          git checkout develop
          git merge origin/main -m "Merge main into develop
          skip-checks: true"
          git push origin develop
        shell: bash

      
      